### Post a (username, password) pair to get a token
POST {{host}}/login
Content-Type: application/json

{
  "username": "test",
  "password": "test"
}

### Get a protected endpoint without any token
GET {{host}}/protected

### Get a protected endpoint with an expired token
GET {{host}}/protected
Authorization: Bearer {{expired_token}}

### Get a protected endpoint with an invalid token
GET {{host}}/protected
Authorization: Bearer {{invalid_token}}

### Get a protected endpoint with a valid token
GET {{host}}/protected
Authorization: Bearer {{valid_token}}
